version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 722136401996.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t nginx .
      - docker tag nginx:latest 722136401996.dkr.ecr.us-west-2.amazonaws.com/nginx-repo:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 722136401996.dkr.ecr.us-west-2.amazonaws.com/nginx-repo:latest

artifacts:
  files:
    - imagedefinitions.json
